FROM node:8.15.1-alpine
LABEL maintainer="me@isaiasvallejos.dev"

# Create app directory
RUN mkdir -p /usr/app
WORKDIR /usr/app

# Copy dependencies files 
COPY ./package* ./

# Install dependencies
RUN npm install --silent

# Copy all files
COPY . .

# Expose ports and start hot loading
EXPOSE 8080
CMD [ "npm", "run", "dev" ]